# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
#     before_all do
#         ENV["FIREBASE_LOGIN_CREDENTIALS"] = "fastlane/firebase_login_credentials.json"
#         ENV["FIREBASE_APP_ID"] = "1:48962475492:android:7994dd436973baee6963f1"
#     end

    ## firebase distribution
    desc "Delivery App to Firebase Distribution"
    lane :beta do |options|
        gradle(task: "clean")
        gradle(task: "assemble", build_type: "Debug")


        # find path apk

        gradle_apk_output_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

        release_note_information =" BRANCH => #{git_branch} - developer: #{last_git_commit[:author]}"
        release_note = "#{release_note_information} \n #{options[:r]}"

        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            apk_path: gradle_apk_output_path,
            release_notes: "#{release_note}",
            groups_file: "fastlane/groups.txt",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
        )
        # firebase testGoogle r: "First Alpha Release"

    end
end
